###端口号配置
server:
  port: 8081
###数据库配置  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
  # 缓存配置读取
  cache:
    jcache:
      config: classpath:/ehcache.xml